library(shiny)
library(shinydashboard)
library(shinyjs)
library(mongolite)
library(leaflet)
library(rgdal)
library(raster)
library(bcrypt)
library(jsonlite)
library(DT)
library(revgeo)
library(plyr)
library(maptools)
library(purrr)
library(tidyr)
library(stringr)
library(dismo)
library(openxlsx)
library(geojsonR)
library(httr)
library(cronR)

source("container/dashboard.R")
source("container/profile.R")
source("container/usergroup.R")
source("container/users.R")
source("container/allAppUsers.R")
source("helper/databaseconnector.R")
source("helper/cache.R")
source("helper/rest.R")

places <- shapefile("../../gis-data/gemeinden/Austria_AL8")
land <- shapefile("../../gis-data/land/Austria_AL2")
bund <- shapefile("../../gis-data/states/Aargau_AL4")
germany <- shapefile("../../gis-data/germany/landkreis_lindau")

################# RELOAD DATA ##########################
cron_clear(ask=FALSE)
cmd <- cron_rscript("autoCacheReload.R")
cron_add(command = cmd, frequency = 'daily', id = 'job_1', at = '23:59', days_of_month = '*')
cron_ls()